### ISSUE TITLE
Error with SS_readdat_3.30() through develop_OMs() 

### ISSUE THREAD

**Issue by rwildermuth** [futureseas/SardineMSE#1]
Trying to use SSMSE, but ran into error trying to apply sardine research model as an OM through develop_OMs(). traceback() led to this error in r4ss::SS_readdat_3.30():

Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument

Seems to be an issue with length composition definitions. @peterkuriyama, do you have this same issue?

**Comment by peterkuriyama** [comment]
Maybe try reading in a dat.ss_new file? It might be the formatting in the dat file causing the snag

**Comment by rwildermuth** [comment]
I believe this was fixed with a bug report and package update to SSMSE.
