### ISSUE TITLE
Trying new EM with run_SSMSE fails at init

### ISSUE THREAD

**Issue by rwildermuth** [futureseas/SardineMSE#3]
In cohortGrowthOM_fixedParamsEM_MSE.R, pointing to the new EM in the EM folder results in all iterations failing at the init phase of the MSE simulation. The EM works well when run through command line within that directory. I also tried running the model specified in the init folder for iteration 1 and it ran outside of SSMSE. 

There are no error folders or files like in previous iteration failures. Unsure how to troubleshoot this. @k-doering-NOAA @nathanvaughan-NOAA do you have any suggestions?

**Comment by k-doering-NOAA** [comment]
@rwildermuth sorry to hear you ran into this problem! The error message should be shown within the list object (I think it is called errored_iterations) created by running `run_SSMSE`. However, sometimes this is not the most helpful. 

I will test your script out, that does sound tricky to troubleshoot.

**Comment by rwildermuth** [comment]
Thank you for your help @k-doering-NOAA. The output to the console shows: 

```
Previous iterations found in folder for scenario cohortGrowthself_compNsamp. First iteration folder will be 6.
Iteration 6 failed in directory C:/Users/rwildermuth/Documents/FutureSeas/SardineMSE/cohortGrowthOMfixedParamsEM/cohortGrowthself_compNsamp. Please delete folders with failed runs before running summary functions.
Completed all iterations for scenario cohortGrowthself_compNsamp
Completed all SSMSE scenarios
```
and the output in the list object is:

`> test1$cohortGrowthself_compNsamp$errored_iterations
  iteration                   scenario
1         6 cohortGrowthself_compNsamp
                                                                                                      out_dir
1 C:/Users/rwildermuth/Documents/FutureSeas/SardineMSE/cohortGrowthOMfixedParamsEM/cohortGrowthself_compNsamp
                                                                                                                                                        error
1 OM_dat and EM_dat should have the same start and end years. However, OM_dat has styr = 1981 and endyr = 2019, while EM_dat has styr = 2000 and endyr = 2019`

We're trying to simulate a situation similar to the current sardine assessment where we have data for past decades, but the assessment begins in 2005. Is there a way to have the EM start in the same year but have empty data, or some kind of mean value?

**Comment by k-doering-NOAA** [comment]
Ah, I see.  So there is early years of data informing the OM, but you don't want to include data for those early years? Does that sound right?

I think we made the assumption that everyone would want their OMs and EMs to start in the same year and erroring if they don't would be helpful, but that probably doesn't need to be the case.  It may be as easy as taking out the stop statement that produces the error message (https://github.com/nmfs-fish-tools/SSMSE/blob/6194035391c9c40319afe1d76a97578e0d53902b/R/checkinput.R#L65-L72) to allow it to work., I'll give that a try tomorrow morning at the lastest!

**Comment by rwildermuth** [comment]
Yes, that's correct. The reasoning is that we're assuming the EM has a limited understanding of the population dynamics simulated in the OM. 

I may try forking the repository to try that edit. I'll keep you updated. 

Thanks again!

**Comment by k-doering-NOAA** [comment]
I just pushed a commit to the main branch of SSMSE to get rid of the error msg - I tested locally and I think that was all that was needed to get it running with your models! Let me know if you find otherwise...

**Comment by rwildermuth** [comment]
This update worked for me too! I've run another set of test iterations using our EM/OM mis-spesification and updated the repository if you're curious how it went.

Thanks again for helping out on short notice.

**Comment by k-doering-NOAA** [comment]
Awesome, thanks for helping us test SSMSE and being patient with the bugs you find!
